import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303031",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-fixed": "#131b2e",
        "secondary-container": "#d5e0f8",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-fixed": "#d5e3fc",
        "surface-container-high": "#e9e8e9",
        "inverse-on-surface": "#f2f0f1",
        "error": "#ba1a1a",
        "outline": "#76777d",
        "inverse-primary": "#bec6e0",
        "on-surface": "#1b1c1d",
        "on-tertiary-fixed": "#0d1c2e",
        "on-tertiary-container": "#77859a",
        "surface-container-low": "#f5f3f4",
        "secondary-fixed-dim": "#bcc7de",
        "primary-fixed": "#dae2fd",
        "on-primary-container": "#7c839b",
        "tertiary-fixed-dim": "#b9c7df",
        "secondary": "#545f73",
        "on-surface-variant": "#45464d",
        "on-error-container": "#93000a",
        "background": "#fbf9fa",
        "surface": "#fbf9fa",
        "on-secondary-fixed": "#111c2d",
        "surface-tint": "#565e74",
        "surface-container-highest": "#e3e2e3",
        "outline-variant": "#c6c6cd",
        "tertiary-container": "#0d1c2e",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3a485b",
        "on-secondary-fixed-variant": "#3c475a",
        "error-container": "#ffdad6",
        "primary-container": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e3e2e3",
        "on-secondary": "#ffffff",
        "surface-bright": "#fbf9fa",
        "secondary-fixed": "#d8e3fb",
        "tertiary": "#000000",
        "surface-container": "#efedee",
        "on-tertiary": "#ffffff",
        "primary": "#000000",
        "on-background": "#1b1c1d",
        "on-error": "#ffffff",
        "surface-dim": "#dbd9db",
        "on-secondary-container": "#586377",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-md": "1rem",
        margin: "1.25rem",
        "space-sm": "0.5rem",
        "margin-desktop": "3.5rem",
        "space-lg": "1.75rem",
        "space-xs": "0.25rem",
        "space-xl": "3rem",
        "gutter-desktop": "2.5rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "display-mobile": ["var(--font-playfair)"],
        "headline-lg-mobile": ["var(--font-playfair)"],
        "body-lg": ["var(--font-jakarta)"],
        "headline-md": ["var(--font-playfair)"],
        "label-sm": ["var(--font-jakarta)"],
        display: ["var(--font-playfair)"],
        "headline-sm": ["var(--font-playfair)"],
        "body-sm": ["var(--font-jakarta)"],
        "title-lg": ["var(--font-jakarta)"],
        "label-md": ["var(--font-jakarta)"],
        "title-md": ["var(--font-jakarta)"],
        "body-md": ["var(--font-jakarta)"],
        "headline-lg": ["var(--font-playfair)"],
      },
      fontSize: {
        "display-mobile": [
          "34px",
          { lineHeight: "42px", letterSpacing: "-0.015em", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "body-lg": [
          "17px",
          { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-md": [
          "26px",
          { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" },
        ],
        display: [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        "body-sm": [
          "13px",
          { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" },
        ],
        "title-lg": [
          "18px",
          { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" },
        ],
        "title-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        "body-md": [
          "15px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
